In [57]:
import pandas as pd

In [58]:
df=pd.read_csv('winemag-data-130k-v2.csv')

In [59]:
#localizar nulos

df.isnull()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,False,False,False,False,False,True,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,True,True,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,False,False,False,False,False,False,False,True,True,False,True,False,False,False
129967,False,False,False,True,False,False,False,False,False,False,False,False,False,False
129968,False,False,False,False,False,False,False,False,True,False,False,False,False,False
129969,False,False,False,True,False,False,False,False,True,False,False,False,False,False
129970,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [60]:
#media dos nulos em porcentagem

df.isnull().mean()

Unnamed: 0               0.000000
country                  0.000485
description              0.000000
designation              0.288257
points                   0.000000
price                    0.069215
province                 0.000485
region_1                 0.163475
region_2                 0.611367
taster_name              0.201922
taster_twitter_handle    0.240154
title                    0.000000
variety                  0.000008
winery                   0.000000
dtype: float64

In [61]:
# descobrir o que a funÃ§Ã£o faz de acordo com o codigo da tarefa 
# importar sklearn importando KBinsDiscretizer
#variavel train faz esclusao dos valores de acordo com dropna com somente valores, com reshape deixa em matriz.
#discretizer chama  a funcao kbindiscretizer
# fit treinamento ultilizo ele con discretizer.fit(train)
# criacao coluna points group e transformo coluna baseado no jÃ¡ feito 


from sklearn.preprocessing import KBinsDiscretizer
train = df.points.dropna().values.reshape(-1,1)
discretizer =KBinsDiscretizer(n_bins=4,encode="ordinal",strategy='uniform')

discretizer.fit(train)


df['points_group']=discretizer.transform(train)*5+80

In [62]:
#retornar valores point group

df['points_group'].value_counts()

85.0    68496
90.0    46629
80.0    12430
95.0     2416
Name: points_group, dtype: int64

In [63]:
# criar variavel df price per group depois dataframe chamando colunas
#agrupou e pegou media da price

df_price_per_group = df[["country", "points_group","price"]].groupby(["country", "points_group"]).mean() 

df_price_per_group

                            price
country   points_group
Argentina 80.0          14.421735
          85.0          19.427708
          90.0          50.348745
          95.0          83.363636
Armenia   85.0          14.500000
...                           ...
Ukraine   80.0           9.300000
          85.0           9.000000
Uruguay   80.0          19.625000
          85.0          25.205882
          90.0          40.764706

[120 rows x 1 columns]

In [64]:
#retornar price e alterar nome da coluna

df_price_per_group.columns=['price_per_group']

In [65]:
# refazer o indice
# subscrever df price

df_price_per_group.reset_index()
df_price_per_group=df_price_per_group.reset_index()

In [66]:
# merge da esquerda onde country e points grupos

df_merge=df.merge(df_price_per_group,how='left',on=['country','points_group'])
df_merge

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,points_group,price_per_group
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",VulkÃ Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin Oâ€™Keefe,@kerinokeefe,Nicosia 2013 VulkÃ Bianco (Etna),White Blend,Nicosia,85.0,28.757327
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,85.0,16.554805
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,85.0,29.088498
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,85.0,29.088498
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,85.0,29.088498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr SpÃ¤tlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben MÃ¼ller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben MÃ¼ller-Burggraef),90.0,47.473684
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation,90.0,47.076489
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,GewÃ¼rztraminer,Domaine Gresser,90.0,53.994993
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,90.0,53.994993
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth CuvÃ©e Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth CuvÃ©e Car...,GewÃ¼rztraminer,Domaine Schoffit,90.0,53.994993

In [67]:
# price do merge onde for fillna price por group e tirou a media
 
df_merge['price'].fillna(df_merge['price_per_group']).mean()

35.60524860764774

Questao 4

In [68]:
import numpy as np
# inicia uma lista vazia onde colocaremos os outliers
outliers = []
df['price']=df['price'].dropna()

# desvio padrÃ£o 
desv_pad = np.std(df['price'])

# mÃ©dia dos seus dados
media = np.mean(df['price'])

# coloca o limite que determina se Ã© outlier
limite = desv_pad * 3

limite_inferior = media - limite
limite_superior = media + limite

# Localiza outliers e anexa Ã  nossa lista que iniciamos sem nada
for outlier in df['price']:
    if outlier > limite_superior or outlier < limite_inferior:
        outliers.append(outlier)


# conta quantos elementos sÃ£o outliers
print(len(outliers))

1177

5.

In [69]:
# principio pareto retorna valores do 8 paises no qual retorna 90% dos  valores
a = df['country'].value_counts()
a = a.reset_index()
soma_primeiros=sum(a.country[0:8])
soma_total =sum(a.country)
soma_primeiros/soma_total*100
a

                     index  country
0                       US    54504
1                   France    22093
2                    Italy    19540
3                    Spain     6645
4                 Portugal     5691
5                    Chile     4472
6                Argentina     3800
7                  Austria     3345
8                Australia     2329
9                  Germany     2165
10             New Zealand     1419
11            South Africa     1401
12                  Israel      505
13                  Greece      466
14                  Canada      257
15                 Hungary      146
16                Bulgaria      141
17                 Romania      120
18                 Uruguay      109
19                  Turkey       90
20                Slovenia       87
21                 Georgia       86
22                 England       74
23                 Croatia       73
24                  Mexico       70
25                 Moldova       59
26                  Brazil       52
27                 Lebanon       35
28                 Morocco       28
29                    Peru       16
30                 Ukraine       14
31                  Serbia       12
32          Czech Republic       12
33               Macedonia       12
34                  Cyprus       11
35                   India        9
36             Switzerland        7
37              Luxembourg        6
38  Bosnia and Herzegovina        2
39                 Armenia        2
40                Slovakia        1
41                   China        1
42                   Egypt        1

In [70]:
# selecionamos os dados com o country igual a US


df_usa=df.loc[df['country']=='US']
#selecionamos o com o numero de registro maior que 100 
a = (df_usa['province'].value_counts())>100

a=a.reset_index()
#criamos uma lista com os estados
lista_paises=list(a['index'].loc[a.province==True])
#contamos o numero de estados na lista
len(lista_paises)

7

A distribuiÃ§Ã£o da variÃ¡vel Price Ã© bastante desnormalizada, como podemos ver na imagem 1. Aplicando a transformaÃ§Ã£o do Box-Cox, podemos melhorar muito sua distribuiÃ§Ã£o como estÃ¡ representado na imagem 2. Assinale o valor do lambda que promoveu essa transformaÃ§Ã£o (lembre de recarregar o dataset original):

In [71]:
#boxcox chama funcao e treina os dados e retorna o lambda
import pandas as pd
import numpy as np
from sklearn.preprocessing import PowerTransformer
boxcox_transformer = PowerTransformer(method='box-cox', standardize=False)
v = df['price'].values.reshape(-1,1)
boxcox_transformer.fit(v)
boxcox_transformer.lambdas_

array([-0.2962151])

 8. Vamos tratar o campo "Description". Assinale o resultado produzido pelo cÃ³digo da imagem ao lado.

In [72]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
import re
from nltk.tokenize import word_tokenize
from nltk.tokenize import TreebankWordTokenizer, WordPunctTokenizer, WhitespaceTokenizer
from nltk.stem import SnowballStemmer
from nltk.corpus import stopwords
import string
import re
snowball_stemmer = SnowballStemmer('portuguese')

def clean_text(sentence):
    word_tokens= word_tokenize(sentence)
    new_words= [word for word in word_tokens if (word not in string.punctuation and not re.match("[0-9]+", word))]
    clean_tokens = new_words[:]
    for token in clean_tokens:
        if token in stopwords.word('english'):
            clean_tokens.remove(token)
    return ' '.join(clean_tokens)  
    
clean_text(df['description'])

lista = [x for x in df['description']]
nova_lista=[]
for i in lista:
    nova_lista.append(clean_text(i))
nova_lista

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Rafael\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Rafael\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

TypeError: expected string or bytes-like object

In [56]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Rafael\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Rafael\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True